name: UnitedWorld

version: 1.0

author: CraftingDani

api-version: 1.19

main: Main

commands:
   pay:
      description: "pay money to other players"
   setmoney:
      description: "set the amount of money for a specific player"
